// Generated by CoffeeScript 1.10.0
var gas;

gas = (function() {
  function gas() {}

  gas._spreadSheet = null;

  gas._sheets = [];

  gas._activeSheetName = null;

  gas.getSpreadSheet = function() {
    if (this._spreadSheet === null) {
      this._spreadSheet = SpreadsheetApp.getActiveSpreadsheet();
    }
    return this._spreadSheet;
  };

  gas.getSheet = function(name) {
    var sheet;
    if (this._sheets[name] != null) {
      return this._sheets[name];
    }
    sheet = this.getSpreadSheet().getSheetByName(name);
    if (!sheet) {
      return null;
    }
    this._sheets[name] = sheet;
    return this._sheets[name];
  };

  gas.setActiveSheet = function(name) {
    if (this.getSheet(name) === null) {
      return false;
    }
    this._activeSheetName = name;
    return true;
  };

  gas.get = function(x, y, name) {
    var sheet;
    if (name == null) {
      name = null;
    }
    if (name === null) {
      name = this._activeSheetName;
    }
    sheet = this.getSheet(name);
    if (sheet === null) {
      return false;
    }
    return sheet.getRange(x + 1, y + 1).getValue();
  };

  gas.set = function(val, x, y, name, xEnd, yEnd) {
    var sheet, xNum, yNum;
    if (name == null) {
      name = null;
    }
    if (xEnd == null) {
      xEnd = null;
    }
    if (yEnd == null) {
      yEnd = null;
    }
    if (name === null) {
      name = this._activeSheetName;
    }
    if (xEnd === null) {
      xEnd = x;
    }
    if (yEnd === null) {
      yEnd = y;
    }
    xNum = xEnd - x + 1;
    yNum = yEnd - y + 1;
    sheet = this.getSheet(name);
    if (sheet === null) {
      return false;
    }
    return sheet.getRange(x + 1, y + 1, xNum, yNum).setValue(val);
  };

  gas.color = function(colorCode, x, y, name, xEnd, yEnd) {
    var sheet, xNum, yNum;
    if (name == null) {
      name = null;
    }
    if (xEnd == null) {
      xEnd = null;
    }
    if (yEnd == null) {
      yEnd = null;
    }
    if (name === null) {
      name = this._activeSheetName;
    }
    if (xEnd === null) {
      xEnd = x;
    }
    if (yEnd === null) {
      yEnd = y;
    }
    xNum = xEnd - x + 1;
    yNum = yEnd - y + 1;
    sheet = this.getSheet(name);
    if (sheet === null) {
      return false;
    }
    return sheet.getRange(x + 1, y + 1, xNum, yNum).setBackground(colorCode);
  };

  gas.clear = function(x, y, name, xEnd, yEnd) {
    var sheet, xNum, yNum;
    if (name == null) {
      name = null;
    }
    if (xEnd == null) {
      xEnd = null;
    }
    if (yEnd == null) {
      yEnd = null;
    }
    if (name === null) {
      name = this._activeSheetName;
    }
    if (xEnd === null) {
      xEnd = x;
    }
    if (yEnd === null) {
      yEnd = y;
    }
    xNum = xEnd - x + 1;
    yNum = yEnd - y + 1;
    sheet = this.getSheet(name);
    if (sheet === null) {
      return false;
    }
    return sheet.getRange(x + 1, y + 1, xNum, yNum).setBackgrounds(colorCode);
  };

  return gas;

})();
